# Generated by Django 3.2 on 2021-06-19 08:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(null=True),
        ),
    ]
